### PR TITLE
Czech localization updates

### PR DESCRIPTION
**Pull request by zoul**
This is a big batch of the remaining Czech localization, mostly the static pages. Once this is merged and online, I will do a final review of the website to make sure everything displays as intended and we’re good to ship.

In 5f0f6b8 I have removed a question from `prototype/jurisdictions/certificate.CZ.xml`. I don’t know if anything needs to be updated or regenerated to reflect the change. Otherwise the changes should be pretty trivial, just updating the localization resources.

### CODE REVIEW

**Comment by pkqk** [comment]
@zoul I'll regenerate the survey file after merging.

So that question branch isn't needed at all?

**Comment by pkqk** [comment]
Also did you do the translation updates for the `yaml` manually or in Transifex and then pulled them down?

That is: do I need to push them to Transifex or is that already done?

**Comment by zoul** [comment]
I initially read the _branch_ word as a Git branch to my great confusion. According to a lawyer we currently don’t need a Privacy Impact Assessment in the Czech jurisdiction, so yes, we don’t need the whole questionnaire branch. (Thinking about it now, we will need to revisit the issue later anyway, since leaving out a question means we won’t have a proper translation when a certificate from a different jurisdiction is displayed in Czech. But that’s not an immediate priority now.)

What could be translated in Transifex was translated in Transifex, so you don’t need to push the changes back there. While we are at it, do you have a script to pull the updated translations from Transifex? Downloading the files by hand and placing them in the proper folders in the repo is a task that’s begging to be automated.

**Comment by pkqk** [comment]
Ah sorry for overloading the word, language is tricky.

I think the translation will be fine, the string will still be in Transifex so even if the Czech questionnaire isn't using the question it's still there to be translated.

To update the yaml files you can install the [Transifex `tx` program](http://docs.transifex.com/client/setup/) then you can update the translations with `tx pull -l cs` or there is a rake task to update it all

    rake translations:pull[CZ]

and if you need to rebuild the questionnaire then

    rake surveyor:build[CZ]

should re-import everything, this should also pull the translations but that might be a bit buggy.

**Comment by pkqk** [comment]
Actually I found this issue #1353 when merging, I'll have a think about how to solve it.

**Comment by zoul** [comment]
Thanks for the rake tip! We need to see the merged changes online so that we can do a final review before we ship. If the #1353 is a blocker, could we help things forward by simply leaving the question there for the moment? Having one English question in the survey is more acceptable for us at the moment than having all the changes blocked.

Second thing: if I have more changes, can I simply push them to the `czech-localization-updates` branch even though it’s already merged? Or is it better to create a new branch and a new PR? (I’m not sure how well repeated merging works.) The changes are trivial, they won’t break anything.

**Comment by pkqk** [comment]
@zoul I think for the moment it might be easiest to bring back the question. We can set it to not being required though if that makes things easier. That won't interfere with the translations.

You can keep pushing them to the `czech-localization-updates` branch but make a new PR once one has been merged.

**Pull request merged**
