### PR TITLE
Add missing responses to campaign view

### LINKED ISSUE #1119: Reporting for automatic certification run
As a portal owner
I want to receive a report showing which datasets have failed to certify using the existing metadata and why
So that I can make changes to them to get the certificates automatically

Initially it will be great to get a report in spread sheet so we can send the report to the portal owner.

Mock-up of the report is available from here:
https://drive.google.com/open?id=1V4pb6PSo4cI2OtJ3ZYA9CkO3X5AmzMbDx-ap6MBt8_4&authuser=0

### PR DESCRIPTION
**Pull request by pezholio**
Fixes #1119

### CODE REVIEW

**Comment by pkqk** [comment]
This is how the code used to do it, and while it works it is too slow once the report is over about 10 certificates so the page repeatedly times out.

We'd need to store the missing questions at the end of generation instead.

**Comment by pezholio** [comment]
Ah, now that I did not know. I'll go back to the drawing board in that case.

**Comment by pkqk** [comment]
Yeah maybe we should have a catchup about tickets tomorrow since there's probably a lot of stuff that's just in my head.

**Comment by pezholio** [comment]
Good plan :+1:

**Comment by pezholio** [comment]
This is good to go now. I've added a Rake task that we'll need to run after deploy has happened (`rake cache:missing_responses`) to cache those responses that haven't already been cached. I did consider putting this in a migration, but I remember that's caused us pain before.

**Comment by pkqk** [comment]
ah, you've set it up to merge into master.

staging is the main branch for merging PRs now, then once staging is signed off I make a PR for master:staging to do a deploy.

You can't change PR destinations so will have to close this and make another.

**Comment by pezholio** [comment]
Ah, that makes sense. I'll close this one then

**Pull request closed without merging**
