### PR TITLE
Speedup Save+Publish actions

### PR DESCRIPTION
**Pull request by pkqk**
Improve the speed of save and publish actions by reducing the amount of work they do re-saving the questionnaire.

### CODE REVIEW

**Comment by Floppy** [comment]
For theodi/shared#686

**Comment by Floppy** [comment]
@pkqk is this mergable yet?

**Comment by pkqk** [comment]
@Floppy this is mergable, there's more I wanted to do but this should solve some of the issues.

**Comment by Floppy** [comment]
Done then.

**Pull request merged**
