### PR TITLE
Fixes #1690. Added status call on api base url returning 404, but sti…

### LINKED ISSUE #1690: Running a campaign not able to validate vanilla ckan api base url
When running a campaign, there is a text input box to enter the base api url.
An example is given:
**http://data.mysite.uk/api**
I notice that when hitting this url you indeed get a json response of {version: .. }

However I'm not sure that this behaviour exists in any of the recent vanilla ckan api docs or code.
An example of a prod website that resembles what I believe is this default api is at:
**https://data.qld.gov.au/api**
This returns a 404.
My own running of local and uat ckan instances also replicates this behaviour.

Code update is needed to perhaps glean this version from another means - I would suggest using the util/status call which will return a {...., ckan_version: .... }.
This could be done on receiving a 404 from a url which has passed preliminary validation.
That way if this status api call was successful and the 'ckan_version' attribute was present, the validation could still pass.

### PR DESCRIPTION
**Pull request by mattRedBox**
…ll with a valid api as is the vanilla ckan behaviour. Reformatted. Unit test added.

This PR fixes #1690 

Changes proposed in this pull request:

- Add status call which exists in vanilla ckan api, containing attribute 'ckan_version'
- Enables successful validation of valid api which does not return response on call to base api
- Added unit test(s)

### CODE REVIEW

**Comment by mattRedBox** [comment]
Hi @olivierthereaux 
Please review when you can.

**Comment by olivierthereaux** [comment]
Apologies for the delay Matt - I was away. Will have a look.

**Comment by olivierthereaux** [comment]
Looks good as far as I can tell. Just one question @mattRedBox - is there any good documentation (or UI) on how the expected URI will be e.g. https://demo.ckan.org/api/ (rather than https://demo.ckan.org/)? Otherwise it may be good to add heuristics to "add" the missing /api WKL.

**Comment by mattRedBox** [comment]
Hi @olivierthereaux 
I may have misunderstood your comment, but as far as I can see, no there's no doco about it really.
Before I had dived into the code, the only clue as to guessing was on the page itself:
image

However the code itself doesn't really care about the URL as such, only that there is the response is application/json with the key: ["version"](https://github.com/theodi/open-data-certificate/blob/staging/lib/odibot.rb#L80).
So a person's attempt to enter a URL, won't stop the app attempting to fetch that response, if that makes sense?

I guess there's nothing to stop a person trying with or without '/api'

**Comment by olivierthereaux** [comment]
Thanks Matt - that bit of UI was what I was trying to remember/find.

**Comment by olivierthereaux** [comment]
Noticed that auto-deploy to https://staging.certificates.theodi.org/ wasn't on. Now fixed.

**Pull request merged**
