### PR TITLE
Czech website translation

### PR DESCRIPTION
**Pull request by zoul**
I have translated the `en.yml` file in Transifex and exported the new `cs.yml` version. After you merge this, will the web start working in Czech, or is there some extra work needed such as #1238? We would love to check the translation out on the live app to weed out bugs.

### CODE REVIEW

**Comment by tonymarklove** [comment]
Closing. This has been merged as part of #1270

**Comment by zoul** [comment]
Perfect! Where/when can we see the results online? The certificates.theodi.org website still seems to be English only, staging.certificates.theodi.org looks broken (unstyled) on my device.

**Comment by tonymarklove** [comment]
I think they should appear on staging.certificates.theodi.org, but you are right it looks broken. I wasn't seeing it because my browser was caching the working version, but I will look into what's happening. I'll send you a follow up message when I get it fixed.

**Comment by tonymarklove** [comment]
@zoul you should be able to see the the Czech translations now on the staging site by going to http://staging.certificates.theodi.org/cs/

**Pull request closed without merging**
