### PR TITLE
Never. Bundle. Again

### PR DESCRIPTION
**Pull request by pkqk**
Run Certificates in Docker.

I've created a `Dockerfile` which the app can run in based on the default `ruby` image and set up a
`docker-compose.yml` file that links the required `redis` and `mysql` services.

Running `bin/dockerize` will set everything up and open the app in your default browser.

**Instructions**

1. Install [Docker Toolbox](https://www.docker.com/products/docker-toolbox)
  * Set up a Docker host with `docker-machine start default` or use Kitematic GUI
  * Make sure your terminal can talk to Docker
    * either by opening the 'Docker Quikstart Terminal'
    * or adding `eval $(docker-machine env default)` to your `.bashrc`
2. run `bin/dockerize`
3. make tea
4. everything should be set up and be open in your browser.

Tests can be run inside a container too with:

    docker-compose run --rm web bundle exec rake test

Once `bin/dockerize` has been run you can stop the system with:

    docker-compose down

and start it again with:

    docker-compose up -d

and open in your browser with:

    bin/open

### CODE REVIEW

**Comment by pkqk** [comment]
what didn't work @pikesley?

**Comment by Floppy** [comment]
@pkqk we're missing a step between installing docker toolbox and being able to run `bin/dockerize`. Error is:

```
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```

@pikesley is working it out now, I think, but if you know the incantation to get it to init the machine, paste it in :)

**Comment by pikesley** [comment]
screenshot 2016-04-07 10 49 00

What am I missing?

**Comment by pkqk** [comment]
Ah, I've had my docker host running all the time so forgot that.

It might take a while for the VM to come up, I set it up using the GUI (Kitematic) which gives you a bit of feedback.

**Comment by pkqk** [comment]
What does `docker-machine status` give you, mine returns `Running`

ah, and then you'll need to tell your terminal how to talk to docker which is:

    eval $(docker-machine env default)

which I have in [my dot-files](https://github.com/pkqk/dot-files/blob/master/bashrc#L75-L78)

**Comment by pkqk** [comment]
@pikesley @Floppy tell me if that works, I've updated the top comment too.

**Comment by pikesley** [comment]
@pkqk I did this thing

    eval $(docker-machine env default)

and it's now doing stuff :)

**Comment by pikesley** [comment]
So, it got *much* further, but:
screenshot 2016-04-07 13 22 39

**Comment by pkqk** [comment]
@pikesley ah, it got half way through last time. `rm config/database.yml` and it will do all the setup again.

**Comment by pikesley** [comment]
l'amaze 
screenshot 2016-04-07 13 53 05

**Comment by pikesley** [comment]
How do I get my gems into `vendor/gems` in the first place?

**Comment by Floppy** [comment]
:heart_decoration: this is amazing

**Comment by pezholio** [comment]
After a bit of to-ing and fro-ing, this works for me too :+1:

**Comment by pkqk** [comment]
Cool, was the problems setting up docker, or is there bits in here that are still missing? @pezholio

**Comment by pkqk** [comment]
@pikesley just saw your gems comment.

`vendor/gems` is just used for the surveyor gem atm so it can be modified but if you wanted to add another one, a `gem unpack` into there should work and then you'd have to run a shell in the web container to run bundle. This is the bit I haven't got all worked out yet.

**Pull request merged**
