### PR TITLE
Use Rails I18n for survey translations

### PR DESCRIPTION
**Pull request by tonymarklove**
This means we no longer use the `survey_translations` database table provided by Surveyor. All localised strings for the surveys are loaded as locale files and provided through `I18n.translate`.

Loading locale files for each language available for each jurisdiction was getting a bit slow, so I have gone further and combined all jurisdictions for a given language into a single locale file. This is almost what Tranisfex wants us to do anyway because there are so many duplicate strings everywhere otherwise.

### CODE REVIEW

**Comment by pkqk** [comment]
There's a few changes here I'm not sure about, we still need to offer the language switching on the `start`/`take` pages as they may not be logged in at that point. Removing the `SurveyTranslation` model has taken away the knowledge of which languages a Survey is intended to be available in (is this going to be in the yaml files/`I18n` backend somewhere)

**Comment by tonymarklove** [comment]
Switching on the `start`/`take` pages is still in there. Did you see it commented out? If so I think that was just me waiting for the other branches to be merged, which you did earlier.

Your other point is the interesting one, which I have been wondering about. Maybe we should discuss what we want to do there. We could just keep a list of supported languages for each jurisdiction and force lookups back to English if they request anything else. But there is also a good chance that a big percentage of the questionnaire will already have translations in the language they want. I don't know if it's better or worse to just show them that.

**Comment by pkqk** [comment]
It was commented out, I see you rebased it.

If we offer everything it becomes a large select list which is a bit annoying. I think there's likely going to be a sensible list of languages for each jurisdiction.

**Comment by tonymarklove** [comment]
Presumably that select list is the same as we will have elsewhere on the app anyway? All those languages will be supported app wide, so I'm not sure how we want to restrict them once they get to the survey. If they had previously selected a language before clicking "Create new certificate" what should we do at that point?

**Comment by pkqk** [comment]
I get what you mean more now, yeah the list is only as big as what we support. Which is about 7 at the moment which isn't so unwieldily.

There will also be the case of people who are filling it in without an account yet.

Perhaps a better UI eg.
`[ Main jurisdiction lang | other jurisdiction lang | English | <dropdown for others> ]`

**Comment by tonymarklove** [comment]
Ok, I have updated the UI for selecting a language within the survey section, based on your idea above: show direct links to all the fully-supported languages for the current jurisdiction but also provide a dropdown to switch to any language if the user wants to do that.

**Pull request merged**
