### PR TITLE
Run campaigns from UI

### PR DESCRIPTION
**Pull request by pezholio**
Logged in users can now create campaigns from the UI, rather than relying on the rake task. Form is pretty lo-fi, but looks like this:

fireshot capture 1 - odi open data certificate - http___open-data-certificate dev_campaigns_new

### CODE REVIEW

**Comment by pkqk** [comment]
Does this limit campaigns to admins?

I think for the moment it should only be for us, we can expand it to portal owners etc later?

**Comment by pkqk** [comment]
Also is there any way to know when a campaign has finished running?

**Comment by pezholio** [comment]
Yeah, limited to Admins at the mo. The only way to find out if it's finished running (currently) is looking at the list and seeing if any are pending. That said, it'd be trivial to do a count (or similar of pending runners). I'll do that now (in the other PR)

**Comment by pkqk** [comment]
"trivial" does sidekiq let you inspect pending jobs.

**Comment by pezholio** [comment]
No, but each created generator has a "completed" flag, so you can do a count of all current generators without the flag applied

**Comment by pkqk** [comment]
The new campaign form doesn't handle the campaign being invalid.

also maybe make the url input wider

**Comment by pezholio** [comment]
Cool. Will crack on with these.

**Pull request merged**
