### PR TITLE
Add Poke to Question ID

### PR DESCRIPTION
**Pull request by Stephen-Gates**
After experimenting in development, the only way I can see to make the <label> and <help> wording changes in the XML to appear on screen is by changing the Question ID. I've appended "Poke" to some question ids. I'd prefer not to do this if there is a better way. Not updating the wording was also present after the last merge of the AU localisation in Staging.

Changing some question ids breaks reading CKAN e.g. publisherRights- see comments in XML. 

Bug #1391 persists and presents a bad user experience. It should be fixed seperately for all certificate users.

Also removing references to theodi.org.au help until the help is finalised.

From development:

CKAN read
screenshot 2018-06-18 06 16 32

Wording changes reflected
screenshot 2018-06-18 06 27 21

Certificate awarded (and warning that the survey changed)
screenshot 2018-06-18 06 18 41

Certificate published 
screenshot 2018-06-18 06 20 05

Campaign run
screenshot 2018-06-18 06 23 14

Certificates automatically awarded
screenshot 2018-06-18 06 24 12

cc: @olivierthereaux @ldodds @mattRedBox

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
Sorry I am a GitHub novice. I'm not sure how to the Travis complaint above

**Comment by olivierthereaux** [comment]
Hi @Stephen-Gates just had a look at this. The Travis CI error does not worry me *too much* - following the link seems to point to some odd git object index corruption but job eventually completes.

That said, it would be better if we could avoid this POKE kludge. How did you figure out that the question identifiers needed to change?

I wonder if @pezholio ran into this issue in the past - whereby a new localisation could not be successfully installed. Stuart, anything you can rememeber and/or any pointer you might have?

**Comment by Stephen-Gates** [comment]
Hi @olivierthereaux 
I agree it is a hack and I'd love to avoid it. I noticed that the same error of not updating the words exists in production with the GB Final survey 

screenshot 2018-06-17 09 12 01

Changing the question id was just an idea to try trigger a change and it worked. This came from the new dataBreach question working fine but others with unchanged question ids not updating. There must be a more correct way to tell the user interface to update itself.

**Comment by Stephen-Gates** [comment]
I forgot to mention that when I removed "Poke" from the question id, the original <label> and <help> values returned to the user interface despite the .xml and generated .rb files appearing correct. 

That suggests to me something is being stored/cached somewhere.

**Comment by olivierthereaux** [comment]
@Stephen-Gates I believe the questions are being stored in the database, yes. Hence the rake tasks, as @mattredbox mentioned.

**Comment by pezholio** [comment]
Hmmmm... it's lost to the annals of time for me I'm afraid. I don't recall having any of these issues though. It might be worth looking at the database and seeing if the IDs have any uniqueness enforced maybe?

**Comment by Stephen-Gates** [comment]
Thanks @pezholio 
@olivierthereaux what do you suggest as the next step?

**Comment by olivierthereaux** [comment]
No magical solution at this very moment @Stephen-Gates but it would be good to open an issue documenting the fact that changes to the questions does not get reflected in the service. Can you do so, and can anyone in your team start investigating?

We may have time in ODI HQ's tech team to look into it, but not before end of week. Meanwhile I'm progressing paperwork on contributor agreements as fast as I can, so your team can at least deploy and test to staging, but given that the issues appear to be consistent with what you had locally, it's not in immediate critical path.

**Comment by olivierthereaux** [comment]
FWIW, I've resolved the Travis conflict by updating the branch. Would be good to make sure to re-synch ODIQueensland/open-data-certificate with upstream.

**Comment by Stephen-Gates** [comment]
Thanks @olivierthereaux 
So will you consider merging and running the build commands for this PR or is the "Poke" hack a show-stopper?

**Comment by olivierthereaux** [comment]
Am clearly not a fan of the hack, but for now mostly curious what you meant by 
> Changing some question ids breaks reading CKAN e.g. publisherRights- see comments in XML

**Comment by Stephen-Gates** [comment]
When I changed the publisherRights question to try force a wording change, in the survey:

- the wording changes where reflected
- but after providing a url to a CKAN dataset, the reading of the dataset metadata did not discover it all and did not award a bronze certificate.

If I reverted the changes:

- the wording didn't change
- the reading of the CKAN metadata awarded a bronze certificate and almost a silver.

I assume some question ids have special meaning and are used elsewhere in the code.

I don't believe CKAN metadata answers any of the Privacy questions so the hack in the Privacy is ok.

I think accepting the PR in staging is low risk as I don't believe it would impact other jurisdictions. 

We're exploring getting a developer to look at the root cause but this will probably not meet our timeline given that we may need to get both code and xml thru staging and production.

**Comment by olivierthereaux** [comment]
I see, thanks @Stephen-Gates. I'm hoping this doesn't cascade into more pain, but I'm happy going ahead with this workaround. Do you think your team can generate the updated .rb and .yml files, as previously? I will then take care of the deployment and rake on the server.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates @olivierthereaux 
.rb and .yaml merged from your recent updates @Stephen-Gates  -pending CI checks

**Comment by olivierthereaux** [comment]
CI passed! I'm merging and deploying to Staging now.

**Comment by Stephen-Gates** [comment]
Thanks @olivierthereaux. Testing in Staging 

CKAN read

screenshot 2018-06-21 06 38 07

Wording changed 

screenshot 2018-06-21 06 41 19

Certificate awarded & warning that survey changed

screenshot 2018-06-21 06 43 16

Certificate published 

screenshot 2018-06-21 06 49 23

Certificate can be viewed 

screenshot 2018-06-21 06 49 50

So looking good. Will test campaigns next.

**Comment by Stephen-Gates** [comment]
Campaign testing...

Create a campaign
screenshot 2018-06-21 06 59 15

Start a campaign

screenshot 2018-06-21 07 00 11

Certificates awarded 

screenshot 2018-06-21 07 02 44

View an automatically awarded certificate 

screenshot 2018-06-21 07 04 31

So at a course level of testing it works!!!

I'll test more thoroughly tonight, I'm away at an off-site event today.

**Comment by Stephen-Gates** [comment]
Same results in staging and prod for other jurisdictions (USA)

Staging
screenshot 2018-06-21 18 44 18

Production
screenshot 2018-06-21 18 43 43

**Comment by Stephen-Gates** [comment]
Line of questioning is correct but #1391 provides a bad user experience
screenshot 2018-06-21 18 50 54

**Comment by Stephen-Gates** [comment]
@olivierthereaux this change works as expected and doesn't seem to break other jurisdictions. Bug #1391 is annoying but has been there since early 2016.

I hope the above screenshots are sufficient evidence to give you confidence to deploy the certificate to Production. 

Are you able change the status to Final and deploy to Production? Then I'll run a campaign.

**Comment by olivierthereaux** [comment]
Looks good, thank for thorough testing. I am afk today so won't get to deploy to production before late afternoon, possibly early tomorrow.

**Comment by Stephen-Gates** [comment]
Great thanks @olivierthereaux

**Pull request merged**
