### PR TITLE
Fixing url resolving test

### PR DESCRIPTION
**Pull request by pkqk**
The locale requirement in urls had broken this hardcoded url. This is just a quick fix until we do something more well thought out.

### CODE REVIEW

**Comment by tonymarklove** [comment]
Seems like I missed a few things with this. I guess test coverage needs to improve around the use of JavaScript.

**Comment by pkqk** [comment]
Yeah, I don't think we have many UI level integration tests at the moment.

**Comment by pkqk** [comment]
I haven't managed to find any other hard coded urls in the javascript though.

**Comment by tonymarklove** [comment]
Cool. Well hopefully that's all of them for now.

**Pull request merged**
