### PR TITLE
First part of the licensing changes for the Czech law system.

### PR DESCRIPTION
**Pull request by pkqk**
These are the new licensing questions adapted to the Czech law
environment. What’s missing are the required certificate levels
and help texts, those will be added later.

### CODE REVIEW

**Comment by pkqk** [comment]
@zoul do you have english translations for the bits that you've changed?

I'd like to merge it in using the new transifex based system if possible.

**Comment by zoul** [comment]
I’ll post the English translation as soon as possible – either later today or tomorrow.

**Comment by zoul** [comment]
See the latest commit (f3b950a). I took the original English legal file and replaced the licensing part with the Czech-specific questions translated back to English. I saved the file here:

    prototype/jurisdictions/certificate.CZ.EN.xml

Feel free to move the content as you see fit.

**Comment by pkqk** [comment]
This will be merged in in the changes for #1203 so that it's using the new Transifex system for translations too.

**Pull request closed without merging**
