### PR TITLE
Campaign defaults

### PR DESCRIPTION
**Pull request by digitalWestie**
Addresses #1413 

Allows user to choose a template response_set when setting up a campaign.

### CODE REVIEW

**Comment by digitalWestie** [comment]
NB - I had some trouble with this earlier today but I was unable to reproduce the error. I'm going to put it down to my environment as when I rebuilt docker instances this all seemed to work fine. Still worth you all keeping an eye on it though!

**Comment by pezholio** [comment]
This works up to a point. I've just tried it with a template, running it against the parliament.uk CKAN instance at http://www.data.parliament.uk/

I set up a template that answers the questions to the publisher name and publisher url questions, adds a custom license (Open Parliament License with the URL http://www.parliament.uk/site-information/copyright/open-parliament-licence/), and answers yes whether it's an open license.

I then run the autocertification with the template and the certificates get created (yay!). However, they don't seem to have a level, but there are no questions missing, see:

fireshot capture 62 - odi open data certificate_ - http___open-data-certificate dev_campaigns_34

When I got in to edit one of the certificates, it _seems_ like all should be well, but when I scroll down to the 'Practical Information' section, it looks like the URLs have either been removed, or not added at all:

fireshot capture 63 - odi open data c_ - http___open-data-certificate dev_en_surveys_rviwotcyhw_take

And:

fireshot capture 64 - odi open data c_ - http___open-data-certificate dev_en_surveys_rviwotcyhw_take

If I add some URLs there and republish, I get a Bronze certificate as expected

**Comment by pezholio** [comment]
Also, rerunning the certification seems to work too

**Comment by digitalWestie** [comment]
Wasn't able to replicate the removed URLs issue. Confirmed that passable certificates weren't getting receiving the proper certificate level.

**Comment by pezholio** [comment]
Nice - this works perfectly with the Parliament data. OK to merge?

**Comment by digitalWestie** [comment]
I think so. I think we just have to be careful what answers we provide in the template given the behaviour around follow up questions like @JeniT suggested. Perhaps there's a way of making this a bit more clever but it works for now. :+1:

**Comment by pezholio** [comment]
Kool and the gang. I'll merge now 😄

**Pull request merged**
