### PR TITLE
Combined jurisdiction translations

### PR DESCRIPTION
**Pull request by tonymarklove**
To prevent the exponential explosion of repeated questions.

The basic outcome of all this is that we have a single `questionnaire.jurisdictions.<lang>.yml` file for each language which contains translations for all jurisdictions.

Nearly all questions are identical between jurisdictions so this is much easier overall.

Once this is merged all the specific jurisdiction resources can be deleted from Transifex as well, which should make the Transifex statistics much more useful.

### CODE REVIEW

**Comment by pkqk** [comment]
@tonymarklove this has conflicts now after merging the de updates.

I guess we have to merge this pretty soon or the `questionnaire.jurisdictions` resource will drift?

**Comment by tonymarklove** [comment]
That would probably make sense, yes. But it's always possible to regenerate everything, so it's not a huge deal.

I'll rebase now, anyway.

**Comment by pkqk** [comment]
Does this depend on #1342? there's lots of removals of `:required => :required`

**Comment by tonymarklove** [comment]
Hmm, not sure why those have ended up changing. It shouldn't actually matter though. They all appear to be on answers, which never had a 'required' column as far as I can tell.

**Pull request merged**
