### PR TITLE
Move CertificateFactory code to the app

### PR DESCRIPTION
**Pull request by pezholio**
This removes a point of failure, and also allows us to kick off campaigns by running a rake task, which then queues everything up in Sidekiq, so we can fire and forget.

Using Sidekiq also has the added advantage of requeuing whenever we encounter an error, so this fixes theodi/shared#642

We can also check on progress in the Sidekiq web frontend (only accessible by admins).

I've kept DelayedJob on board too for now, as I didn't want to get too bogged down in transitioning to Sidekiq for this piece of work. Everything should work fine still though.

I still need to spin up a RedisToGo instance and add that to the Chef Envs, so this isn't *quite* ready to merge. Will probably give it a try in staging too.

### CODE REVIEW

**Comment by pezholio** [comment]
I've just checked and RedisToGo won't let us have more than one Micro (free) instance, which is fair enough. I can't imagine we'll need a massive one, so can probably go for the $4 a month plan. That sound OK?

**Comment by pezholio** [comment]
I'm also thinking, do we want to always use campaigns for the bulk imports now? It would certainly make sense - we could autogenerate a name (probably based on the current datetime) if one isn't specified

**Comment by pkqk** [comment]
Looks mostly good.

There are few things I think we might need to check though. So Sidekiq guarantees that a job will be run *at least once* (which means they can be run more than once – because of CAP)* which means we'll need to check that all the generation tasks don't leave things lying around if they fail, and they a transactional and can prevent double running if they start up together and if it starts again after the other one has finished it either updates the previously made certificate or skips the task.

* ignoring the fact that Redis is not reliable and can just loose data when it starts hitting it's memory limit.

**Comment by pkqk** [comment]
@pezholio re: campaigns, I think we need to think about what use cases the are for bulk imports.

Currently it's used for bulk loading a portal and that's it. This isn't a thing that I think should be dated and treated as a once off as that's not how @sumikasan and the portal owners have been treating it. More of a initial go, fix problems and retry until happy with result.

So I think it should be more thought of as setting up a recurring import task, so the name should be along the lines of the Portal, or search subset of Portal, and should have the ability to see report and errors from dashboard.

Ideally the task should be startable from the site too as if the rake task is in the app now, that requires sshing into one of the boxes to run it then doesn't it?

**Comment by pezholio** [comment]
Yeah, the idea was to start with a rake task and then add user-facing stuff later. But I see what you mean about portals and naming etc. I guess this can come later too, as it's probably out of scope for this sprint.

**Comment by pkqk** [comment]
Another thing we'll need to do, not for this ticket though is read the CKAN api to get the list instead of the atom feed as not all installs have the atom feeds turned on (particularly data.gov)

**Comment by pkqk** [comment]
adding another reminder (idea dumping again sorry)

We need to account for requests to pages in atom feed etc failing as they do regularly too. So maybe the initial sidekiq job should be load first page of feed and queue up generation tasks for each url, then instead of looping onto next page that should kick off a separate job with the new url so it can be retried by sidekiq.

**Comment by pezholio** [comment]
Gonna close this one and move to https://github.com/theodi/open-data-certificate/pull/1172 to get ready to move into staging

**Pull request closed without merging**
